server:
  port: 8082
  servlet:
    context-path: /app
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=market-autumn
    username: postgres
    password:
  jpa:
    database: POSTGRESQL
    show-sql: true